apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp
  namespace: default
spec:
  secretName: myapp-tls
  issuerRef:
    name: vault-issuer
  commonName: myapp.st_login.rebrain.me
  dnsNames:
  - myapp.st_login.rebrain.me